CREATE DATABASE INFOGALAXY;

USE INFOGALAXY;

CREATE TABLE STUDENT(
	ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    AGE INT,
    EMAIL VARCHAR(150) UNIQUE,
    ADMISSIONDATE DATE
);

SELECT * FROM STUDENT;

ALTER TABLE STUDENT ADD GENDER VARCHAR(100);

ALTER TABLE STUDENT MODIFY AGE SMALLINT;

ALTER TABLE STUDENT MODIFY AGE INT;

ALTER TABLE STUDENT CHANGE COLUMN NAME FULLNAME VARCHAR(100);

ALTER TABLE STUDENT DROP COLUMN GENDER;

ALTER TABLE STUDENT ADD GENDER VARCHAR(100);

SELECT * FROM STUDENT;

INSERT INTO STUDENT(ID,FULLNAME,AGE,EMAIL,ADMISSIONDATE,GENDER)
VALUES (101,"YASH_PATIL",20,"SUMIT@123",'2004-01-01',"MALE");


UPDATE STUDENT SET EMAIL="YASH15@GMAIL.COM" WHERE ID=101;

INSERT INTO STUDENT(ID,FULLNAME,AGE,EMAIL,ADMISSIONDATE,GENDER)
VALUES (102,"SUMIT_PATIL",20,"YASH@123",'2025-05-21',"MALE");
INSERT INTO STUDENT(ID,FULLNAME,AGE,EMAIL,ADMISSIONDATE,GENDER)
VALUES (103,"YOGESH_BADGUJAR",20,"YOGESH@123",'2004-09-30',"MALE");

SELECT * FROM STUDENT;

UPDATE STUDENT SET AGE=21 WHERE ID=102;

INSERT INTO STUDENT(ID,FULLNAME,AGE,EMAIL,ADMISSIONDATE, GENDER)
VALUES (104,"OM_TAYDE",19,"OM@1234",'2006-01-01',"MALE");

CREATE TABLE STUDENTINFO(
	ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    AGE INT,
    EMAIL VARCHAR(100) UNIQUE,
    GENDER VARCHAR(100) NOT NULL,
    DEPT_ID INT,
    CHECK(AGE>18),
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID)
);

CREATE TABLE DEPARTMENTS(
	DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(200) NOT NULL,
    DEPT_HEAD VARCHAR(255) NOT NULL
);

SELECT * FROM STUDENTINFO;
SELECT * FROM DEPARTMENTS;

INSERT INTO STUDENTINFO(ID,NAME,EMAIL,AGE,GENDER,DEPT_ID)
VALUES(101,"YASH","YASH@123",20,"MALE",1001);

INSERT INTO STUDENTINFO(ID,NAME,EMAIL,AGE,GENDER,DEPT_ID)
VALUES(102,"YOGESH","YOGESH@123",21,"MALE",1001);

INSERT INTO STUDENTINFO(ID,NAME,EMAIL,AGE,GENDER,DEPT_ID)
VALUES(103,"OM","OM@123",19,"MALE",1002);

INSERT INTO STUDENTINFO(ID,NAME,EMAIL,AGE,GENDER,DEPT_ID)
VALUES(104,"MOKSH","MOKSH@123",19,"MALE",1002);

INSERT INTO STUDENTINFO(ID,NAME,EMAIL,AGE,GENDER,DEPT_ID)
VALUES(105,"CHETAN","CHETAN@123",19,"MALE",1004);

INSERT INTO STUDENTINFO(ID,NAME,EMAIL,AGE,GENDER,DEPT_ID)
VALUES(106,"RAJ","RAJ@123",22,"MALE",1003);

INSERT INTO STUDENTINFO(ID,NAME,EMAIL,AGE,GENDER,DEPT_ID)
VALUES(107,"PUJA","PUJA@123",20,"FEMALE",1001);

INSERT INTO STUDENTINFO(ID,NAME,EMAIL,AGE,GENDER,DEPT_ID)
VALUES(108,"JAYU","JAYU@123",20,"FEMALE",1002);

INSERT INTO STUDENTINFO(ID,NAME,EMAIL,AGE,GENDER,DEPT_ID)
VALUES(110,"KIRTI","KIRTI@123",21,"FEMALE",1003);


INSERT INTO DEPARTMENTS(DEPT_ID,DEPT_NAME,DEPT_HEAD)
VALUES(1001,"COMPUTER_SCIENCE","S.S.BHAMARE");

INSERT INTO DEPARTMENTS(DEPT_ID,DEPT_NAME,DEPT_HEAD)
VALUES(1002,"SOCIAL_LIFE_SCIENCE","PURANIK SIR");

INSERT INTO DEPARTMENTS(DEPT_ID,DEPT_NAME,DEPT_HEAD)
VALUES(1003,"BIOTECHNOLOGY","BUSHAN CHAUDHARI SIR");

INSERT INTO DEPARTMENTS(DEPT_ID,DEPT_NAME,DEPT_HEAD)
VALUES(1004,"ELECTRONICS","D.J. SHIRADE SIR");

SELECT * FROM DEPARTMENTS;
SELECT * FROM STUDENTINFO;

ALTER TABLE STUDENTINFO ADD COUNTRY VARCHAR(100) DEFAULT 'INDIA';
ALTER TABLE DEPARTMENTS ADD ADDRESS VARCHAR(100) DEFAULT 'NMU,JALGAON';

ALTER TABLE STUDENTINFO DROP ADDRESS;

SELECT NAME FROM STUDENTINFO;
SELECT ID FROM STUDENTINFO;
SELECT EMAIL FROM STUDENTINFO;
SELECT NAME FROM STUDENTINFO WHERE AGE>18;

SELECT * FROM STUDENTINFO ORDER BY AGE DESC;

SELECT DISTINCT GENDER FROM STUDENTINFO;
SELECT DISTINCT NAME FROM STUDENTINFO;
SELECT DISTINCT DEPT_NAME FROM DEPARTMENTS;

SELECT GENDER, COUNT(*) AS STUNDENTCOUNT
FROM STUDENTINFO
GROUP BY GENDER;

SELECT AGE, COUNT(*) AS STUDENTCOUNT
FROM STUDENTINFO
GROUP BY AGE;

SELECT DEPT_ID, COUNT(*) AS StudentCount FROM STUDENTINFO GROUP BY DEPT_ID;

SELECT AVG(AGE) AS AVERAGE_AGE FROM STUDENTINFO;

SELECT COUNT(*) AS TOTAL_STUDENT FROM STUDENTINFO;

SELECT MAX(AGE) AS ELDER_STUDENT FROM STUDENTINFO;

SELECT MIN(AGE) AS YOUNG_STUDENT FROM STUDENTINFO;

SELECT SUM(AGE) AS TOTAL_OF_AGE FROM STUDENTINFO;

SELECT ASCII('A');
SELECT ASCII('Z');
SELECT ASCII('a');
SELECT ASCII('z');
SELECT ASCII('@');
SELECT ASCII('%');

-- RANDOM FUNCTION IN MYSQL --

ALTER TABLE STUDENTINFO ADD SCORE VARCHAR(100); 
SELECT * FROM STUDENTINFO;


UPDATE STUDENTINFO SET SCORE=RAND();
SELECT * FROM STUDENTINFO;

ALTER TABLE STUDENTINFO MODIFY SCORE INT;
SELECT * FROM STUDENTINFO;
UPDATE STUDENTINFO SET SCORE=RAND();
SELECT * FROM STUDENTINFO;

ALTER TABLE STUDENTINFO DROP SCORE;

ALTER TABLE STUDENTINFO ADD COLUMN SCORE INT;
SELECT * FROM STUDENTINFO;

UPDATE STUDENTINFO SET SCORE = FLOOR(1+(RAND()*100));

SELECT * FROM STUDENTINFO;

SELECT ID,NAME,SCORE, 
COUNT(*) AS STUDENTCOUNT 
FROM STUDENTINFO WHERE SCORE>60 AND SCORE<90 GROUP BY ID,NAME,SCORE;

ALTER TABLE STUDENTINFO ADD ADDRESS VARCHAR(150);
SELECT * FROM STUDENTINFO;

UPDATE STUDENTINFO SET ADDRESS=CONCAT("LOCATION_",FLOOR(RAND() * 1000));
SELECT * FROM STUDENTINFO;

CREATE VIEW STUDENT AS SELECT ID,NAME,ADDRESS FROM STUDENTINFO;
SELECT * FROM STUDENT;

RENAME TABLE STUDENT TO STUDENT_VIEW;
SELECT * FROM STUDENT_VIEW;

ALTER TABLE STUDENTINFO ADD PRN INT;
SELECT * FROM STUDENTINFO;

UPDATE STUDENTINFO SET PRN=now()+FLOOR(RAND()*10);
SELECT * FROM STUDENTINFO;

ALTER TABLE STUDENTINFO MODIFY PRN VARCHAR(150);
UPDATE STUDENTINFO SET PRN=now()+FLOOR(RAND()+10);
SELECT * FROM STUDENTINFO;

UPDATE STUDENTINFO SET PRN=null;
SELECT * FROM STUDENTINFO;

UPDATE STUDENTINFO SET PRN = FLOOR(now()+1+(RAND()*100));
SELECT * FROM STUDENTINFO;

DESC STUDENTINFO;
SHOW COLUMNS FROM STUDENTINFO;

-- Re Order the Columns in Existing Table in MYSQL ---

ALTER TABLE STUDENTINFO MODIFY EMAIL VARCHAR(100) AFTER PRN;
SELECT * FROM STUDENTINFO;

ALTER TABLE STUDENTINFO MODIFY PRN VARCHAR(150) AFTER ID;
ALTER TABLE STUDENTINFO MODIFY EMAIL VARCHAR(100) AFTER GENDER;
ALTER TABLE STUDENTINFO MODIFY ADDRESS VARCHAR(150) AFTER EMAIL;
ALTER TABLE STUDENTINFO MODIFY COUNTRY VARCHAR(100) AFTER ADDRESS;
SELECT * FROM STUDENTINFO;